add modal when sending to the user that hasn't own a wallet
myriadsocial/myriad-web pull request #1381
Opened 2022-07-19 07:37 UTC by rofisudiyono

## Describe your changes

## Issue ticket number / link
https://blocksphere2020.atlassian.net/browse/MYR-2309 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2022-07-19 10:33 UTC, abdulhakim2902 requested changes

2022-07-19 10:33 UTC, abdulhakim2902 commented on src/components/common/Tipping/render/Summary/Summary.tsx
> +            {` ${currency.symbol} `}
Please change `currency.symbol` 
The wallet is something like this [MYRIAD APP](https://app.testnet.myriad.social/wallet?type=manage)
Network MYRIAD, KUSAMA, and POLKADOT using  polkadot{.js}
Network NEAR using NEAR wallet

2022-07-19 10:33 UTC, abdulhakim2902 commented on src/components/common/Tipping/render/Summary/Summary.tsx
> +            Wallet yet. Once they connect their {` ${currency.symbol} `} Wallet, they will be able
Please change `currency.symbol` 
The wallet is something like this [MYRIAD APP](https://app.testnet.myriad.social/wallet?type=manage)
Network MYRIAD, KUSAMA, and POLKADOT using polkadot{.js}
Network NEAR using NEAR wallet

2022-07-20 00:41 UTC, abdulhakim2902 approved these changes

2022-07-21 00:24 UTC, kriptonhaz approved these changes

2022-07-21 00:24 UTC, merged