feat: added view button in trending experience
myriadsocial/myriad-web pull request #1426
Opened 2022-08-02 08:17 UTC by immhrmwn

## Describe your changes
- [fix: removed scroll horizontal bar](https://github.com/myriadsocial/myriad-web/commit/18fef6c6396b4c574ff747dd58dbdba8693ab9e8)
- [feat: add view button in trending experience](https://github.com/myriadsocial/myriad-web/commit/835bfdd6a15225cab2afa1d480e44b18b9ec0552)
## Issue ticket number / link
- https://blocksphere2020.atlassian.net/browse/MYR-2414?atlOrigin=eyJpIjoiNzgzYjIwMDUxNmJmNGM5NGJjYTJmMzFkY2M0NTA3YzAiLCJwIjoiaiJ9
- https://blocksphere2020.atlassian.net/browse/MYR-2387?atlOrigin=eyJpIjoiNjdlN2NiYjY1MmNkNGYyMWJlMjllMDk3Nzg0NmYxNmQiLCJwIjoiaiJ9
## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2022-08-03 06:30 UTC, mucktar13 requested changes

2022-08-03 06:30 UTC, mucktar13 commented on src/components/ExperienceList/ExperienceList.container.tsx
> +  const renderLoadMoreButton = () => {
@immhrmwn kayaknya kita punya yang sama di load more comment

enaknya sih di pisahin komponennya. load more comment sama experience pake yang sama

2022-08-04 07:40 UTC, kriptonhaz approved these changes

2022-08-04 07:55 UTC, mucktar13 approved these changes

2022-08-04 08:04 UTC, merged