MYR-341: close post create component on sucess
myriadsocial/myriad-web pull request #224
Opened 2021-07-08 15:32 UTC by mucktar13

Changes

1. Close post modal after post successfully created
2. Disable "Post Now" button on submit, to prevent multiple submission.
3. Add loading indicator on sumbit progress.

2021-07-09 07:50 UTC, rei-gun requested changes

2021-07-09 07:50 UTC, rei-gun commented on src/components/post/create/create-post-expanded.component.tsx
> +  ({ onSubmit, text, user }: CreatePostExpandedComponentProps, ref: React.Ref<CreatePostExpandedComponentRefProps>) => {
Not  a fan of this passing of `user` around. can we put it in the global store/state?

2021-07-09 07:50 UTC, rei-gun commented on src/components/post/create/create-post-expanded.component.tsx
> +    const [submitting, setSubmitting] = useState(false);
use `isSubmitting` because `set` is an action word and should be used for functions

2021-07-09 07:50 UTC, rei-gun commented on src/components/post/create/create-post.component.tsx
> +  const [submitting, setSubmitting] = useState(false);
```suggestion
  const [submitting, isSubmitting] = useState(false);
```

2021-07-13 03:59 UTC, irmannmal approved these changes
need new ticket for reduce user parsing to component, use state instead of parsing data

2021-07-13 04:01 UTC, merged