MYR-716: created prompt container component
myriadsocial/myriad-web pull request #392
Opened 2021-08-31 13:58 UTC by immhrmwn

2021-08-31 14:11 UTC, ical10 commented
Besok pagi gue cek bro, gue ada edit default theme-nya buat font size dll.

2021-09-01 01:42 UTC, mucktar13 commented
kayaknya ga perlu bikin custom component untuk button bro @immhrmwn , cukup edit theme aja

2021-09-01 07:39 UTC, ical10 requested changes

2021-09-01 07:39 UTC, ical10 commented on src/components-v2/prompt/prompt.component.tsx
>  type Prompt = {
ini bisa dipindah ke file Prompt.interfaces.ts?
biar modular

2021-09-01 07:39 UTC, ical10 commented on src/components-v2/prompt/prompt.component.tsx
>    );
ini bagusnya di-refactor lagi kalo Modal Container Component udah ada. Bisa tinggalin TODO ga? Biar gak lupa.

2021-09-01 08:36 UTC, merged