created status banner
myriadsocial/myriad-web pull request #623
Opened 2021-11-09 03:37 UTC by immhrmwn

# Title
- [ ] JIRA Issue ID (preferably only ONE parent issue, put subtask IDs in the Description)
- [ ] Multiple JIRA Issue IDs? Are you sure your PR isn't too big? Can you rebase your commits to new branches so there's only 1 issue ID?
- [ ] Is your title relatable to the JIRA issue?
- [ ] Title <= 100 characters
MYR-1189: created status banner
# Description
 - created status banner
 - put the status banner on home page

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Builds and runs on Chrome Desktop
- [ ] Builds and runs on Chrome Responsive
- [ ] Unit tests?
- [ ] Integration tests?
- [ ] End-to-end (E2E) tests?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Have you added yourself as the Assignee?
- [ ] Have you added 1 or more leads as the Reviewer?
- [ ] Have you chosen 1-2 of the following labels?
  - Feature
  - Bug
  - Refactor
  - Test
  - Documentation

2021-11-09 06:45 UTC, ical10 approved these changes

2021-11-10 03:46 UTC, irmannmal requested changes

2021-11-10 03:46 UTC, irmannmal commented on src/components-v2/atoms/BannerStatus/BannerStatus.tsx
> +      <ShowIf condition={open && appStatus === 'development'}>
change this to != production

2021-11-10 03:59 UTC, immhrmwn commented on src/components-v2/atoms/BannerStatus/BannerStatus.tsx
> +      <ShowIf condition={open && appStatus === 'development'}>
updated

2021-11-10 04:05 UTC, irmannmal approved these changes

2021-11-10 04:17 UTC, merged