Implemented load more with loading state when searching for more users
myriadsocial/myriad-web pull request #947
Opened 2022-02-09 10:23 UTC by ical10

# Title
- [x] JIRA Issue ID (preferably only ONE parent issue, put subtask IDs in the Description)
- [ ] Multiple JIRA Issue IDs? Are you sure your PR isn't too big? Can you rebase your commits to new branches so there's only 1 issue ID?
- [x] Is your title relatable to the JIRA issue?
- [x] Title <= 100 characters

# Description
- Implemented clickable Link `Load more` which will load more searched users onClick
- Adjusted styling on searched users list

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Builds and runs on Chrome Desktop
- [x] Builds and runs on Chrome Responsive
- [ ] Unit tests?
- [ ] Integration tests?
- [ ] End-to-end (E2E) tests?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Have you added yourself as the Assignee?
- [x] Have you added 1 or more leads as the Reviewer?
- [x] Have you chosen 1-2 of the following labels?
  - Feature
  - Bug
  - Refactor
  - Test
  - Documentation

2022-02-09 15:13 UTC, mucktar13 requested changes

2022-02-09 15:13 UTC, mucktar13 commented on src/components/UsersList/UsersList.tsx
> +                  <div className={classes.footer}>
@ical10 disini udah bisa pake `UsersListItem.skeleton`

2022-02-10 04:12 UTC, ical10 commented on src/components/UsersList/UsersList.tsx
> +                  <div className={classes.footer}>
lagi belum pake skeleton dulu mas buat loadingnya

2022-02-10 05:04 UTC, kriptonhaz approved these changes

2022-02-10 05:18 UTC, merged