fix search friend styling
myriadsocial/myriad-web pull request #953
Opened 2022-02-14 08:00 UTC by immhrmwn

# Title
- [ ] JIRA Issue ID (preferably only ONE parent issue, put subtask IDs in the Description)
- [ ] Multiple JIRA Issue IDs? Are you sure your PR isn't too big? Can you rebase your commits to new branches so there's only 1 issue ID?
- [ ] Is your title relatable to the JIRA issue?
- [ ] Title <= 100 characters

# Description
- fix search friend styling

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Builds and runs on Chrome Desktop
- [ ] Builds and runs on Chrome Responsive
- [ ] Unit tests?
- [ ] Integration tests?
- [ ] End-to-end (E2E) tests?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Have you added yourself as the Assignee?
- [ ] Have you added 1 or more leads as the Reviewer?
- [ ] Have you chosen 1-2 of the following labels?
  - Feature
  - Bug
  - Refactor
  - Test
  - Documentation

2022-02-15 08:25 UTC, mucktar13 requested changes

2022-02-15 08:25 UTC, mucktar13 commented on src/components/atoms/Search/SearchBox.tsx
> +    <Paper className={`${reverse && classes.outline} ${classes.root}`} elevation={reverse ? 0 : 1}>
@immhrmwn lebih baik bungkus dalam `<Grid container flexDirection={reverse ? "row-reverse" : "row"} >`

2022-02-16 02:22 UTC, ical10 approved these changes

2022-02-16 04:47 UTC, mucktar13 approved these changes
ntaps

2022-02-16 04:59 UTC, merged